import 'dart:io';

import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class PdfService {
  PdfService._();

  static final PdfService instance = PdfService._();

  Future<File> generateTripReport({
    required String patientName,
    required String driverName,
    required String ambulanceNo,
    required String hospitalName,
    required String emergencyType,
    required String status,
    required double distance,
    required int duration,
    required double fare,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          pw.Header(
            level: 0,
            child: pw.Text(
              "AI Ambulance Emergency Report",
              style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
            ),
          ),

          pw.SizedBox(height: 20),

          _row("Patient", patientName),
          _row("Driver", driverName),
          _row("Ambulance", ambulanceNo),
          _row("Hospital", hospitalName),
          _row("Emergency", emergencyType),
          _row("Status", status),
          _row("Distance", "${distance.toStringAsFixed(2)} km"),
          _row("Duration", "$duration min"),
          _row("Fare", "₹ ${fare.toStringAsFixed(2)}"),

          pw.Divider(),

          pw.SizedBox(height: 20),

          pw.Text(
            "Generated by AI Ambulance & Emergency Response System",
            style: const pw.TextStyle(fontSize: 12),
          ),
        ],
      ),
    );

    final directory = await getApplicationDocumentsDirectory();

    final file = File(
      "${directory.path}/Trip_Report_${DateTime.now().millisecondsSinceEpoch}.pdf",
    );

    await file.writeAsBytes(await pdf.save());

    return file;
  }

  pw.Widget _row(String title, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 6),
      child: pw.Row(
        children: [
          pw.Expanded(
            flex: 2,
            child: pw.Text(
              title,
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            ),
          ),
          pw.Expanded(flex: 3, child: pw.Text(value)),
        ],
      ),
    );
  }
}
