// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC11dmPTQfPFGfgmpQxM9zIBN-Nrjp2az4',
    appId: '1:46016047762:web:fbe642378254563f2c144b',
    messagingSenderId: '46016047762',
    projectId: 'ai-ambulance-app-805d2',
    authDomain: 'ai-ambulance-app-805d2.firebaseapp.com',
    storageBucket: 'ai-ambulance-app-805d2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoBLUOLQCTkRG2pRt1o6JPEoPLAhWarWw',
    appId: '1:46016047762:android:0f0672ba08e1a69c2c144b',
    messagingSenderId: '46016047762',
    projectId: 'ai-ambulance-app-805d2',
    storageBucket: 'ai-ambulance-app-805d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0g98tKMDjp3vnejpX3basdahsvesD4ps',
    appId: '1:46016047762:ios:d24fa71e4a8169f82c144b',
    messagingSenderId: '46016047762',
    projectId: 'ai-ambulance-app-805d2',
    storageBucket: 'ai-ambulance-app-805d2.firebasestorage.app',
    iosBundleId: 'com.example.ambulanceAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0g98tKMDjp3vnejpX3basdahsvesD4ps',
    appId: '1:46016047762:ios:d24fa71e4a8169f82c144b',
    messagingSenderId: '46016047762',
    projectId: 'ai-ambulance-app-805d2',
    storageBucket: 'ai-ambulance-app-805d2.firebasestorage.app',
    iosBundleId: 'com.example.ambulanceAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC11dmPTQfPFGfgmpQxM9zIBN-Nrjp2az4',
    appId: '1:46016047762:web:0c815a8b32d681f62c144b',
    messagingSenderId: '46016047762',
    projectId: 'ai-ambulance-app-805d2',
    authDomain: 'ai-ambulance-app-805d2.firebaseapp.com',
    storageBucket: 'ai-ambulance-app-805d2.firebasestorage.app',
  );
}
